
#dpi: 300
antialias: best

# Text hints are used to show the boundaries of text boxes.
# Can be enabled/disabled at the command-level, or set globally with `set`
#text_hint: '#F00'

# Show progress bars on the command line for potentially long-running operations
#progress_bars: true

#Enable some custom colors that can be used in any color
#custom_colors:
#  foo: '#abc'

custom_colors:
  agile_color: '#2B00B5'
  metrology_color: '#8C00BE'
  continuous_delivery_color: '#EB0085'
  testing_color: '#FF0000'
  code_quality_color: '#FF7F00'
  collaboration_color: '#FFE800'
  bizdev_partnership_color: '#AAFF00'
  leadership_color: '#00C951'
  people_color: '#0090FF'

  light_text: '#F3EFE3'
  medium_text: '#e6e6e6'
  dark_text: '#000000'


warn_ellipsize: true
warn_png_scale: true
