
#dpi: 300
antialias: best

# Text hints are used to show the boundaries of text boxes.
# Can be enabled/disabled at the command-level, or set globally with `set`
#text_hint: '#F00'

# Show progress bars on the command line for potentially long-running operations
#progress_bars: true

#Enable some custom colors that can be used in any color
#custom_colors:
#  foo: '#abc'

custom_colors:
  agile_color: '#440154'
  leadership_color: '#472c7a'
  bizdev_partnership_color: '#3b518b'
  collaboration_color: '#2c718e'
  continuous_delivery_color: '#21908d'
  metrology_color: '#27ad81'
  testing_color: '#5cc863'
  code_quality_color: '#aadc32'
  people_color: '#fde725'

  light_text: '#F3EFE3'
  medium_text: '#e6e6e6'
  dark_text: '#000000'

#- Bleu (1) :
#- Rouille (2) : C47401
#- Rouge (3) : CD3349
#- Violet (4) : 8F074B
#- Vert (5) : 1E7C66
#- Anthracite (6) : 3B3B3B



warn_ellipsize: true
warn_png_scale: true
