
#dpi: 300
antialias: best
backend: svg
warn_ellipsize: false

# Text hints are used to show the boundaries of text boxes.
# Can be enabled/disabled at the command-level, or set globally with `set`
#text_hint: '#F00'

# Show progress bars on the command line for potentially long-running operations
#progress_bars: true

#Enable some custom colors that can be used in any color
#custom_colors:
#  foo: '#abc'

custom_colors:
  application_color: '#FF8000'
  infrastructure_color: '#0080FF'
  environment_color: '#00FF80'

  light_text: '#FFFFFF'
  dark_text: '#000000'


warn_ellipsize: true
warn_png_scale: true
